// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: api/grpc/metrics.proto

package grpcmetrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип метрики
type MetricType int32

const (
	MetricType_GAUGE   MetricType = 0
	MetricType_COUNTER MetricType = 1
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	MetricType_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_api_grpc_metrics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_metrics_proto_rawDescGZIP(), []int{0}
}

// Описание метрики
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          MetricType             `protobuf:"varint,2,opt,name=type,proto3,enum=grpcmetrics.MetricType" json:"type,omitempty"`
	Delta         int64                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`  // для counter
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"` // для gauge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_api_grpc_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_GAUGE
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Запрос отправки одной метрики
type UpdateMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricRequest) Reset() {
	*x = UpdateMetricRequest{}
	mi := &file_api_grpc_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricRequest) ProtoMessage() {}

func (x *UpdateMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

// Ответ от сервера
type UpdateMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // пустой, если success = true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricResponse) Reset() {
	*x = UpdateMetricResponse{}
	mi := &file_api_grpc_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricResponse) ProtoMessage() {}

func (x *UpdateMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetricResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateMetricResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Запрос на отправку батча
type UpdateMetricsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsBatchRequest) Reset() {
	*x = UpdateMetricsBatchRequest{}
	mi := &file_api_grpc_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsBatchRequest) ProtoMessage() {}

func (x *UpdateMetricsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsBatchRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMetricsBatchRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Ответ на батч
type UpdateMetricsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsBatchResponse) Reset() {
	*x = UpdateMetricsBatchResponse{}
	mi := &file_api_grpc_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsBatchResponse) ProtoMessage() {}

func (x *UpdateMetricsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsBatchResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMetricsBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateMetricsBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_grpc_metrics_proto protoreflect.FileDescriptor

const file_api_grpc_metrics_proto_rawDesc = "" +
	"\n" +
	"\x16api/grpc/metrics.proto\x12\vgrpcmetrics\"q\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.grpcmetrics.MetricTypeR\x04type\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x03R\x05delta\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"B\n" +
	"\x13UpdateMetricRequest\x12+\n" +
	"\x06metric\x18\x01 \x01(\v2\x13.grpcmetrics.MetricR\x06metric\"F\n" +
	"\x14UpdateMetricResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"J\n" +
	"\x19UpdateMetricsBatchRequest\x12-\n" +
	"\ametrics\x18\x01 \x03(\v2\x13.grpcmetrics.MetricR\ametrics\"L\n" +
	"\x1aUpdateMetricsBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*$\n" +
	"\n" +
	"MetricType\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x012\xcc\x01\n" +
	"\x0eMetricsService\x12S\n" +
	"\fUpdateMetric\x12 .grpcmetrics.UpdateMetricRequest\x1a!.grpcmetrics.UpdateMetricResponse\x12e\n" +
	"\x12UpdateMetricsBatch\x12&.grpcmetrics.UpdateMetricsBatchRequest\x1a'.grpcmetrics.UpdateMetricsBatchResponseB\x0fZ\r./grpcmetricsb\x06proto3"

var (
	file_api_grpc_metrics_proto_rawDescOnce sync.Once
	file_api_grpc_metrics_proto_rawDescData []byte
)

func file_api_grpc_metrics_proto_rawDescGZIP() []byte {
	file_api_grpc_metrics_proto_rawDescOnce.Do(func() {
		file_api_grpc_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_metrics_proto_rawDesc), len(file_api_grpc_metrics_proto_rawDesc)))
	})
	return file_api_grpc_metrics_proto_rawDescData
}

var file_api_grpc_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_grpc_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_grpc_metrics_proto_goTypes = []any{
	(MetricType)(0),                    // 0: grpcmetrics.MetricType
	(*Metric)(nil),                     // 1: grpcmetrics.Metric
	(*UpdateMetricRequest)(nil),        // 2: grpcmetrics.UpdateMetricRequest
	(*UpdateMetricResponse)(nil),       // 3: grpcmetrics.UpdateMetricResponse
	(*UpdateMetricsBatchRequest)(nil),  // 4: grpcmetrics.UpdateMetricsBatchRequest
	(*UpdateMetricsBatchResponse)(nil), // 5: grpcmetrics.UpdateMetricsBatchResponse
}
var file_api_grpc_metrics_proto_depIdxs = []int32{
	0, // 0: grpcmetrics.Metric.type:type_name -> grpcmetrics.MetricType
	1, // 1: grpcmetrics.UpdateMetricRequest.metric:type_name -> grpcmetrics.Metric
	1, // 2: grpcmetrics.UpdateMetricsBatchRequest.metrics:type_name -> grpcmetrics.Metric
	2, // 3: grpcmetrics.MetricsService.UpdateMetric:input_type -> grpcmetrics.UpdateMetricRequest
	4, // 4: grpcmetrics.MetricsService.UpdateMetricsBatch:input_type -> grpcmetrics.UpdateMetricsBatchRequest
	3, // 5: grpcmetrics.MetricsService.UpdateMetric:output_type -> grpcmetrics.UpdateMetricResponse
	5, // 6: grpcmetrics.MetricsService.UpdateMetricsBatch:output_type -> grpcmetrics.UpdateMetricsBatchResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_grpc_metrics_proto_init() }
func file_api_grpc_metrics_proto_init() {
	if File_api_grpc_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_metrics_proto_rawDesc), len(file_api_grpc_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_metrics_proto_goTypes,
		DependencyIndexes: file_api_grpc_metrics_proto_depIdxs,
		EnumInfos:         file_api_grpc_metrics_proto_enumTypes,
		MessageInfos:      file_api_grpc_metrics_proto_msgTypes,
	}.Build()
	File_api_grpc_metrics_proto = out.File
	file_api_grpc_metrics_proto_goTypes = nil
	file_api_grpc_metrics_proto_depIdxs = nil
}
