// Code generated by MockGen. DO NOT EDIT.
// Source: transport_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/iudanet/yp-metrics-go/internal/models"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// PushMetric mocks base method.
func (m *MockTransport) PushMetric(ctx context.Context, metric models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMetric", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMetric indicates an expected call of PushMetric.
func (mr *MockTransportMockRecorder) PushMetric(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMetric", reflect.TypeOf((*MockTransport)(nil).PushMetric), ctx, metric)
}

// PushMetricsBatch mocks base method.
func (m *MockTransport) PushMetricsBatch(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMetricsBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMetricsBatch indicates an expected call of PushMetricsBatch.
func (mr *MockTransportMockRecorder) PushMetricsBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMetricsBatch", reflect.TypeOf((*MockTransport)(nil).PushMetricsBatch), ctx, metrics)
}
