// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/iudanet/yp-metrics-go/internal/models"
)

// MockMetricReader is a mock of MetricReader interface.
type MockMetricReader struct {
	ctrl     *gomock.Controller
	recorder *MockMetricReaderMockRecorder
}

// MockMetricReaderMockRecorder is the mock recorder for MockMetricReader.
type MockMetricReaderMockRecorder struct {
	mock *MockMetricReader
}

// NewMockMetricReader creates a new mock instance.
func NewMockMetricReader(ctrl *gomock.Controller) *MockMetricReader {
	mock := &MockMetricReader{ctrl: ctrl}
	mock.recorder = &MockMetricReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricReader) EXPECT() *MockMetricReaderMockRecorder {
	return m.recorder
}

// GetCounter mocks base method.
func (m *MockMetricReader) GetCounter(ctx context.Context, name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockMetricReaderMockRecorder) GetCounter(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockMetricReader)(nil).GetCounter), ctx, name)
}

// GetGauge mocks base method.
func (m *MockMetricReader) GetGauge(ctx context.Context, name string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, name)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockMetricReaderMockRecorder) GetGauge(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockMetricReader)(nil).GetGauge), ctx, name)
}

// GetMapCounter mocks base method.
func (m *MockMetricReader) GetMapCounter(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapCounter", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapCounter indicates an expected call of GetMapCounter.
func (mr *MockMetricReaderMockRecorder) GetMapCounter(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapCounter", reflect.TypeOf((*MockMetricReader)(nil).GetMapCounter), ctx)
}

// GetMapGauge mocks base method.
func (m *MockMetricReader) GetMapGauge(ctx context.Context) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapGauge", ctx)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapGauge indicates an expected call of GetMapGauge.
func (mr *MockMetricReaderMockRecorder) GetMapGauge(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapGauge", reflect.TypeOf((*MockMetricReader)(nil).GetMapGauge), ctx)
}

// MockMetricWriter is a mock of MetricWriter interface.
type MockMetricWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMetricWriterMockRecorder
}

// MockMetricWriterMockRecorder is the mock recorder for MockMetricWriter.
type MockMetricWriterMockRecorder struct {
	mock *MockMetricWriter
}

// NewMockMetricWriter creates a new mock instance.
func NewMockMetricWriter(ctrl *gomock.Controller) *MockMetricWriter {
	mock := &MockMetricWriter{ctrl: ctrl}
	mock.recorder = &MockMetricWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricWriter) EXPECT() *MockMetricWriterMockRecorder {
	return m.recorder
}

// LoadDB mocks base method.
func (m *MockMetricWriter) LoadDB(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDB", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadDB indicates an expected call of LoadDB.
func (mr *MockMetricWriterMockRecorder) LoadDB(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDB", reflect.TypeOf((*MockMetricWriter)(nil).LoadDB), ctx, name)
}

// SaveDB mocks base method.
func (m *MockMetricWriter) SaveDB(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDB", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDB indicates an expected call of SaveDB.
func (mr *MockMetricWriterMockRecorder) SaveDB(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDB", reflect.TypeOf((*MockMetricWriter)(nil).SaveDB), ctx, name)
}

// SetCounter mocks base method.
func (m *MockMetricWriter) SetCounter(ctx context.Context, name string, value int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCounter", ctx, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCounter indicates an expected call of SetCounter.
func (mr *MockMetricWriterMockRecorder) SetCounter(ctx, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCounter", reflect.TypeOf((*MockMetricWriter)(nil).SetCounter), ctx, name, value)
}

// SetGauge mocks base method.
func (m *MockMetricWriter) SetGauge(ctx context.Context, name string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", ctx, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockMetricWriterMockRecorder) SetGauge(ctx, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockMetricWriter)(nil).SetGauge), ctx, name, value)
}

// WriteBatch mocks base method.
func (m *MockMetricWriter) WriteBatch(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBatch indicates an expected call of WriteBatch.
func (mr *MockMetricWriterMockRecorder) WriteBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBatch", reflect.TypeOf((*MockMetricWriter)(nil).WriteBatch), ctx, metrics)
}

// MockMetricPersistent is a mock of MetricPersistent interface.
type MockMetricPersistent struct {
	ctrl     *gomock.Controller
	recorder *MockMetricPersistentMockRecorder
}

// MockMetricPersistentMockRecorder is the mock recorder for MockMetricPersistent.
type MockMetricPersistentMockRecorder struct {
	mock *MockMetricPersistent
}

// NewMockMetricPersistent creates a new mock instance.
func NewMockMetricPersistent(ctrl *gomock.Controller) *MockMetricPersistent {
	mock := &MockMetricPersistent{ctrl: ctrl}
	mock.recorder = &MockMetricPersistentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricPersistent) EXPECT() *MockMetricPersistentMockRecorder {
	return m.recorder
}

// LoadDB mocks base method.
func (m *MockMetricPersistent) LoadDB(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDB", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadDB indicates an expected call of LoadDB.
func (mr *MockMetricPersistentMockRecorder) LoadDB(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDB", reflect.TypeOf((*MockMetricPersistent)(nil).LoadDB), ctx, name)
}

// SaveDB mocks base method.
func (m *MockMetricPersistent) SaveDB(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDB", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDB indicates an expected call of SaveDB.
func (mr *MockMetricPersistentMockRecorder) SaveDB(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDB", reflect.TypeOf((*MockMetricPersistent)(nil).SaveDB), ctx, name)
}

// MockCounterIncrementer is a mock of CounterIncrementer interface.
type MockCounterIncrementer struct {
	ctrl     *gomock.Controller
	recorder *MockCounterIncrementerMockRecorder
}

// MockCounterIncrementerMockRecorder is the mock recorder for MockCounterIncrementer.
type MockCounterIncrementerMockRecorder struct {
	mock *MockCounterIncrementer
}

// NewMockCounterIncrementer creates a new mock instance.
func NewMockCounterIncrementer(ctrl *gomock.Controller) *MockCounterIncrementer {
	mock := &MockCounterIncrementer{ctrl: ctrl}
	mock.recorder = &MockCounterIncrementerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterIncrementer) EXPECT() *MockCounterIncrementerMockRecorder {
	return m.recorder
}

// IncrCounter mocks base method.
func (m *MockCounterIncrementer) IncrCounter(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrCounter", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrCounter indicates an expected call of IncrCounter.
func (mr *MockCounterIncrementerMockRecorder) IncrCounter(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrCounter", reflect.TypeOf((*MockCounterIncrementer)(nil).IncrCounter), ctx, name)
}

// MockHealthcheckDB is a mock of HealthcheckDB interface.
type MockHealthcheckDB struct {
	ctrl     *gomock.Controller
	recorder *MockHealthcheckDBMockRecorder
}

// MockHealthcheckDBMockRecorder is the mock recorder for MockHealthcheckDB.
type MockHealthcheckDBMockRecorder struct {
	mock *MockHealthcheckDB
}

// NewMockHealthcheckDB creates a new mock instance.
func NewMockHealthcheckDB(ctrl *gomock.Controller) *MockHealthcheckDB {
	mock := &MockHealthcheckDB{ctrl: ctrl}
	mock.recorder = &MockHealthcheckDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthcheckDB) EXPECT() *MockHealthcheckDBMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockHealthcheckDB) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockHealthcheckDBMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockHealthcheckDB)(nil).Ping), ctx)
}

// MockBatchWriter is a mock of BatchWriter interface.
type MockBatchWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBatchWriterMockRecorder
}

// MockBatchWriterMockRecorder is the mock recorder for MockBatchWriter.
type MockBatchWriterMockRecorder struct {
	mock *MockBatchWriter
}

// NewMockBatchWriter creates a new mock instance.
func NewMockBatchWriter(ctrl *gomock.Controller) *MockBatchWriter {
	mock := &MockBatchWriter{ctrl: ctrl}
	mock.recorder = &MockBatchWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchWriter) EXPECT() *MockBatchWriterMockRecorder {
	return m.recorder
}

// WriteBatch mocks base method.
func (m *MockBatchWriter) WriteBatch(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBatch indicates an expected call of WriteBatch.
func (mr *MockBatchWriterMockRecorder) WriteBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBatch", reflect.TypeOf((*MockBatchWriter)(nil).WriteBatch), ctx, metrics)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetCounter mocks base method.
func (m *MockRepository) GetCounter(ctx context.Context, name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockRepositoryMockRecorder) GetCounter(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockRepository)(nil).GetCounter), ctx, name)
}

// GetGauge mocks base method.
func (m *MockRepository) GetGauge(ctx context.Context, name string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, name)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockRepositoryMockRecorder) GetGauge(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockRepository)(nil).GetGauge), ctx, name)
}

// GetMapCounter mocks base method.
func (m *MockRepository) GetMapCounter(ctx context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapCounter", ctx)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapCounter indicates an expected call of GetMapCounter.
func (mr *MockRepositoryMockRecorder) GetMapCounter(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapCounter", reflect.TypeOf((*MockRepository)(nil).GetMapCounter), ctx)
}

// GetMapGauge mocks base method.
func (m *MockRepository) GetMapGauge(ctx context.Context) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapGauge", ctx)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapGauge indicates an expected call of GetMapGauge.
func (mr *MockRepositoryMockRecorder) GetMapGauge(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapGauge", reflect.TypeOf((*MockRepository)(nil).GetMapGauge), ctx)
}

// IncrCounter mocks base method.
func (m *MockRepository) IncrCounter(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrCounter", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrCounter indicates an expected call of IncrCounter.
func (mr *MockRepositoryMockRecorder) IncrCounter(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrCounter", reflect.TypeOf((*MockRepository)(nil).IncrCounter), ctx, name)
}

// LoadDB mocks base method.
func (m *MockRepository) LoadDB(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDB", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadDB indicates an expected call of LoadDB.
func (mr *MockRepositoryMockRecorder) LoadDB(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDB", reflect.TypeOf((*MockRepository)(nil).LoadDB), ctx, name)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}

// SaveDB mocks base method.
func (m *MockRepository) SaveDB(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDB", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDB indicates an expected call of SaveDB.
func (mr *MockRepositoryMockRecorder) SaveDB(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDB", reflect.TypeOf((*MockRepository)(nil).SaveDB), ctx, name)
}

// SetCounter mocks base method.
func (m *MockRepository) SetCounter(ctx context.Context, name string, value int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCounter", ctx, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCounter indicates an expected call of SetCounter.
func (mr *MockRepositoryMockRecorder) SetCounter(ctx, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCounter", reflect.TypeOf((*MockRepository)(nil).SetCounter), ctx, name, value)
}

// SetGauge mocks base method.
func (m *MockRepository) SetGauge(ctx context.Context, name string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetGauge", ctx, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockRepositoryMockRecorder) SetGauge(ctx, name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockRepository)(nil).SetGauge), ctx, name, value)
}

// WriteBatch mocks base method.
func (m *MockRepository) WriteBatch(ctx context.Context, metrics []models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteBatch indicates an expected call of WriteBatch.
func (mr *MockRepositoryMockRecorder) WriteBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBatch", reflect.TypeOf((*MockRepository)(nil).WriteBatch), ctx, metrics)
}
